services:
    victoire_page.user_callable:
        class: Victoire\Bundle\PageBundle\Helper\UserCallableHelper
        arguments:
            - "@service_container"

    page.subscriber:
        class: Victoire\Bundle\PageBundle\EventSubscriber\PageSubscriber
        arguments:
            - "@router"
            - "@victoire_page.user_callable"
            - "%victoire_core.user_class%"
            - "@victoire_core.view_cache_helper"
            - "@victoire_core.view_url_helper"
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: -1 }

    victoire_page.page_helper:
        class: Victoire\Bundle\PageBundle\Helper\PageHelper
        arguments:
            - "@victoire_business_entity_page.business_entity_page_helper"
            - "@doctrine.orm.entity_manager"
            - "@victoire_core.current_view"
            - "@event_dispatcher"
            - "@victoire_templating"
            - "@victoire_seo.helper.pageseo_helper"
            - "@victoire_core.view_cache_helper"
            - "@session"
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "@victoire_widget_map.builder"
            - "@victoire_business_entity.converter.parameter_converter"
            - "@victoire_core.helper.business_entity_helper"
            - "@victoire_core.view_cache_helper"

    victoire_page.matcher.url_matcher:
        class: Victoire\Bundle\PageBundle\Matcher\UrlMatcher
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@victoire_core.view_url_helper"
            - "@victoire_business_entity_page.business_entity_page_helper"
            - "@victoire_core.helper.business_entity_helper"

    ####################################################################################################################
    # Security voter
    ####################################################################################################################
    page.security.voter.page_owner:
        class: Victoire\Bundle\PageBundle\Security\Voter\PageOwnerVoter
        arguments: ['%victoire_core.user_class%']
        tags:
            - { name: security.voter }
    page.security.voter.page_debug:
        class: Victoire\Bundle\PageBundle\Security\Voter\PageDebugVoter
        arguments: ['%victoire_core.user_class%']
        tags:
            - { name: security.voter }
    ####################################################################################################################
    # Forms
    ####################################################################################################################

    victoire_page.page.form.type:
        class: Victoire\Bundle\PageBundle\Form\PageType
        arguments:
            - "%victoire_i18n.available_locales%"
            - "@request_stack"
        tags:
            - { name: form.type, alias: victoire_page_type }

    victoire_page.page_settings.form.type:
        class: Victoire\Bundle\PageBundle\Form\PageSettingsType
        arguments:
            - "%victoire_i18n.available_locales%"
            - "@request_stack"
        tags:
            - { name: form.type, alias: victoire_page_settings_type }


    ####################################################################################################################
    # Menu
    ####################################################################################################################

    victoire_core.page_menu_listener:
        class: Victoire\Bundle\PageBundle\Listener\PageMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.build_menu, method: addGlobal, priority: 100 }

    victoire_core.page_menu.contextual:
        class: Victoire\Bundle\PageBundle\Listener\PageMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.page_menu.contextual, method: addContextual }

    ####################################################################################################################
    # twig
    ####################################################################################################################

    victoire_page.twig.page_extension:
        class: Victoire\Bundle\PageBundle\Twig\Extension\PageExtension
        arguments:
            - "@victoire_business_entity_page.business_entity_page_helper"
            - "@router"
            - "@victoire_page.page_helper"
        tags:
            - { name: twig.extension }
