services:
    victoire_page.user_callable:
        class: Victoire\Bundle\PageBundle\Helper\UserCallableHelper
        arguments: 
            - "@service_container"

    page.subscriber:
        class: Victoire\Bundle\PageBundle\EventSubscriber\PageSubscriber
        arguments:
            - "@victoire_core.cache.route_registerer"
            - "@router"
            - "@victoire_page.user_callable"
            - "%victoire_core.user_class%"
            - "@service_container"
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: -1 }

    page.widgetMap.builder:
        class: Victoire\Bundle\PageBundle\WidgetMap\WidgetMapBuilder
        arguments:
            - "@doctrine.orm.entity_manager"

    victoire_page.page_helper:
        class: Victoire\Bundle\PageBundle\Helper\PageHelper
        arguments:
            - "@victoire_business_entity.converter.parameter_converter"
            - "@victoire_core.helper.business_entity_helper"
    victoire_page.url_helper:
        class: Victoire\Bundle\PageBundle\Helper\UrlHelper
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
        calls:
            - [setRequest, ["@request_stack"]]

    ####################################################################################################################
    # Security voter
    ####################################################################################################################
    page.security.voter.page_owner:
        class: Victoire\Bundle\PageBundle\Security\Voter\PageOwnerVoter
        arguments: ['%victoire_core.user_class%']
        tags:
            - { name: security.voter }
    page.security.voter.page_debug:
        class: Victoire\Bundle\PageBundle\Security\Voter\PageDebugVoter
        arguments: ['%victoire_core.user_class%']
        tags:
            - { name: security.voter }
    ####################################################################################################################
    # Forms
    ####################################################################################################################

    victoire_page.page.form.type:
        class: Victoire\Bundle\PageBundle\Form\PageType
        arguments: ['%victoire_core.layouts%']
        tags:
            - { name: form.type, alias: victoire_page_type }

    victoire_page.template.form.type:
        class: Victoire\Bundle\PageBundle\Form\TemplateType
        arguments: ['%victoire_core.layouts%']
        tags:
            - { name: form.type, alias: victoire_template_type }

    victoire_page.page_settings.form.type:
        class: Victoire\Bundle\PageBundle\Form\PageSettingsType
        arguments: ['%victoire_core.layouts%']
        tags:
            - { name: form.type, alias: victoire_page_settings_type }


    ####################################################################################################################
    # Menu
    ####################################################################################################################

    victoire_core.page_menu_listener:
        class: Victoire\Bundle\PageBundle\Listener\PageMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
    victoire_core.template_menu_listener:
        class: Victoire\Bundle\PageBundle\Listener\TemplateMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
  
    ####################################################################################################################
    # twig
    ####################################################################################################################

    victoire_page.twig.page_extension:
        class: Victoire\Bundle\PageBundle\Twig\Extension\PageExtension
        arguments: 
            - "@victoire_business_entity_template.business_entity_template_helper"
        tags:
            - { name: twig.extension }