services:

    victoire_page.user_callable:
        class: Victoire\Bundle\PageBundle\Helper\UserCallableHelper
        arguments: [@service_container]

    page.subscriber:
        class: Victoire\Bundle\PageBundle\EventSubscriber\PageSubscriber
        arguments:
            - @victoire_cms.cache.route_registerer
            - @router
            - @victoire_page.user_callable
            - "%victoire_cms.user_class%"
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: -1 }

    page.widgetMap.builder:
        class: Victoire\Bundle\PageBundle\WidgetMap\WidgetMapBuilder



    ####################################################################################################################
    # Security voter
    ####################################################################################################################
    page.security.voter.page_owner:
        class: Victoire\Bundle\PageBundle\Security\Voter\PageOwnerVoter
        arguments: ['%victoire_cms.user_class%']
        tags:
            - { name: security.voter }

    ####################################################################################################################
    # Forms
    ####################################################################################################################

    victoire_page.page.form.type:
        class: Victoire\Bundle\PageBundle\Form\PageType
        arguments: ['%victoire_cms.layouts%']
        tags:
            - { name: form.type, alias: victoire_page_type }

    victoire_page.page_settings.form.type:
        class: Victoire\Bundle\PageBundle\Form\PageSettingsType
        arguments: ['%victoire_cms.layouts%']
        tags:
            - { name: form.type, alias: victoire_page_settings_type }
