language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - npm install less
  - composer install --dev --prefer-dist
  # Prepare database
  - php Tests/Functionnal/bin/console cache:clear --env=test
  - php Tests/Functionnal/bin/console doctrine:database:create --env=test
  - php Tests/Functionnal/bin/console doctrine:schema:create --env=test
  - php Tests/Functionnal/bin/console victoire:generate:view --env=test
  - php Tests/Functionnal/bin/console doctrine:fixtures:load --fixtures="Bundle/CoreBundle/DataFixtures/ORM" -n --append --env=test
  # Run selenium server
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar"
  - "java -jar selenium-server-standalone-2.44.0.jar > /dev/null &"
  - sleep 5


script:
  - 'phpunit --coverage-text'
  - './vendor/bin/behat'


notifications:
    hipchat:
        rooms:
            - 32c78704ec6fd7ad1445cf106d1107@Victoire