services:
    victoire_widget_map.builder:
        class: Victoire\Bundle\WidgetMapBundle\Builder\WidgetMapBuilder
        arguments:
            - "@victoire_widget_map.helper"

    victoire_widget_map.manager:
        class: Victoire\Bundle\WidgetMapBundle\Manager\WidgetMapManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@victoire_widget_map.builder"

    victoire_widget_map.helper:
        class: Victoire\Bundle\WidgetMapBundle\Helper\WidgetMapHelper
        arguments:
            - "@doctrine.orm.entity_manager"
