services:
    victoire_blog.blog_menu_listener:
        class: Victoire\Bundle\BlogBundle\Listener\BlogMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.build_menu, method: addGlobal, priority: 90 }

    victoire_core.blog_menu.contextual:
        class: Victoire\Bundle\BlogBundle\Listener\BlogMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.article_menu.contextual, method: addContextual}

    victoire_blog.base_page.subscriber: #REVIEW surement prendre une convention
        class: Victoire\Bundle\BlogBundle\EventSubscriber\LoadMetadataSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    victoire_blog.category_filters.form.type:
        class: Victoire\Bundle\BlogBundle\Filter\CategoryFilter
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request="
        tags:
            - { name: form.type, alias: category_filter }
            - { name: victoire_core.filter }
    victoire_blog.tag_filters.form.type:
        class: Victoire\Bundle\BlogBundle\Filter\TagFilter
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request="
        tags:
            - { name: form.type, alias: tag_filter }
            - { name: victoire_core.filter }

    ####################################################################################################################
    # Forms
    ####################################################################################################################

    victoire_blog.article.form.type:
        class: Victoire\Bundle\BlogBundle\Form\ArticleType
        arguments: ['%victoire_core.layouts%']
        tags:
            - { name: form.type, alias: victoire_article_type }
