services:
    victoire_blog.blog_menu_listener:
        class: Victoire\Bundle\BlogBundle\Listener\BlogMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.build_menu, method: addGlobal, priority: 90 }

    victoire_core.article_menu.contextual:
        class: Victoire\Bundle\BlogBundle\Listener\BlogMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.article_menu.contextual, method: addContextual}

    victoire_core.blog_menu.contextual:
        class: Victoire\Bundle\BlogBundle\Listener\BlogMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.blog_menu.contextual, method: addBlogContextual}

    ####################################################################################################################
    # Forms
    ####################################################################################################################
    #TREE EXTENSION
    victoire_blog.hierarchy_tree_extension:
        class: Victoire\Bundle\BlogBundle\Form\Extension\HierarchyTreeExtension
        arguments: [ "@property_accessor" ]
        tags:
            - { name: form.type, alias: hierarchy_tree }
    #CATEGORY
    victoire.form.blog.category:
        class: Victoire\Bundle\BlogBundle\Form\CategoryType
        tags:
            - { name: form.type , alias: victoire_form_blog_category}
    #ARTICLE
    victoire_blog.article.form.type:
        class: Victoire\Bundle\BlogBundle\Form\ArticleType
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%victoire_i18n.available_locales%"
            - "@request_stack"
        tags:
            - { name: form.type, alias: victoire_article_type }

    victoire_blog.article_settings.form.type:
        class: Victoire\Bundle\BlogBundle\Form\ArticleSettingsType
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%victoire_i18n.available_locales%"
            - "@request_stack"
        tags:
            - { name: form.type, alias: victoire_article_settings_type }

    victoire_blog.type.tags:
        class: Victoire\Bundle\BlogBundle\Form\TagsType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: tags }

    #BLOG
    victoire_blog.blog.form.type:
        class: Victoire\Bundle\BlogBundle\Form\BlogType
        arguments:
            - "%victoire_i18n.available_locales%"
            - "@request_stack"
        tags:
            - { name: form.type, alias: victoire_blog_type }

    victoire_blog.blog_settings.form.type:
        class: Victoire\Bundle\BlogBundle\Form\BlogSettingsType
        arguments:
            - "%victoire_i18n.available_locales%"
            - "@request_stack"
        tags:
            - { name: form.type, alias: victoire_blog_settings_type }

    #CATEGORY FILTER
    victoire_blog.category_filters.form.type:
        class: Victoire\Bundle\BlogBundle\Filter\CategoryFilter
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request="
        tags:
            - { name: form.type, alias: category_filter }
            - { name: victoire_core.filter }

    #TAG FILTER
    victoire_blog.tag_filters.form.type:
        class: Victoire\Bundle\BlogBundle\Filter\TagFilter
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request="
        tags:
            - { name: form.type, alias: tag_filter }
            - { name: victoire_core.filter }
