parameters:
    Victoire_media.media_manager.class: 'Victoire\Bundle\MediaBundle\Helper\MediaManager'
    Victoire_media.menu.adaptor.class: 'Victoire\Bundle\MediaBundle\Helper\Menu\MediaMenuAdaptor'
    Victoire_media.listener.doctrine.class: 'Victoire\Bundle\MediaBundle\EventListener\DoctrineMediaListener'
    Victoire_media.form.type.media.class: 'Victoire\Bundle\MediaBundle\Form\Type\MediaType'
    Victoire_media.media_creator_service.class: 'Victoire\Bundle\MediaBundle\Helper\Services\MediaCreatorService'
    Victoire_media.menubuilder.class: 'Victoire\Bundle\MediaBundle\Helper\Menu\MenuBuilder'


services:
    liip_imagine.data.loader.stream.profile_photos:
        class: "%liip_imagine.data.loader.stream.class%"
        arguments:
            - "@liip_imagine"
            - ''
        tags:
            - { name: 'liip_imagine.data.loader', loader: 'Victoire_media_thumbloader' }

    Victoire_media.media_manager:
        class: "%Victoire_media.media_manager.class%"

    Victoire_media.menu.adaptor:
        class: "%Victoire_media.menu.adaptor.class%"
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            -  { name: 'Victoire_media.menu.adaptor' }

    Victoire_media.listener.doctrine:
        class: "%Victoire_media.listener.doctrine.class%"
        arguments: ["@Victoire_media.media_manager"]
        tags:
            - { name: 'doctrine.event_listener', event: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'preUpdate' }
            - { name: 'doctrine.event_listener', event: 'postPersist' }
            - { name: 'doctrine.event_listener', event: 'postUpdate' }
            - { name: 'doctrine.event_listener', event: 'preRemove' }

    form.type.media:
        class: "%Victoire_media.form.type.media.class%"
        arguments:
            - "@Victoire_media.media_manager"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: media }

    Victoire_media.media_creator_service:
        class: "%Victoire_media.media_creator_service.class%"
        calls:
            - [ setEntityManager, [ "@doctrine.orm.entity_manager" ] ]

    Victoire_media.menubuilder:
        class: "%Victoire_media.menubuilder.class%"
        arguments: ["@translator", "@service_container"]

    Victoire_media.menu.twig.extension:
        class: Victoire\Bundle\MediaBundle\Twig\MenuTwigExtension
        arguments: ["@Victoire_media.menubuilder"]
        tags:
            -  { name: 'twig.extension' }

    victoire_core.media_menu_listener:
        class: Victoire\Bundle\MediaBundle\EventListener\MediaMenuListener
        arguments:
            - "@victoire_core.admin_menu_builder"
            - "@event_dispatcher"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

