services:

    victoire_i18n.locale_resolver:
        class: Victoire\Bundle\I18nBundle\Resolver\LocaleResolver
        arguments: ['%locale_pattern%', '%locale_pattern_table%', '%locale%']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    victoire_i18n.menu_listener:
        class: Victoire\Bundle\I18nBundle\Listener\I18nMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.page_menu.contextual, method: addContextual, priority: 100 }

    victoire_i18n.url.resolver:
        class: Victoire\Bundle\I18nBundle\Resolver\UrlResolver
        arguments: ["@victoire_page.page_helper", "@doctrine.orm.entity_manager"]
