services:

    victoire_i18n.locale_resolver:
        class: Victoire\Bundle\I18nBundle\Resolver\LocaleResolver
        arguments: ['%locale_pattern%', '%locale_pattern_table%', '%locale%', '%victoire_locale%']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    victoire_i18n.menu_listener:
        class: Victoire\Bundle\I18nBundle\Listener\I18nPageMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.page_menu.contextual, method: addContextual, priority: 100 }

    victoire_i18n.url.resolver:
        class: Victoire\Bundle\I18nBundle\Resolver\UrlResolver
        arguments: ["@victoire_page.page_helper", "@doctrine.orm.entity_manager"]

    victoire_i18n.cache_warmer.i18n_warmer:
        class: Victoire\Bundle\I18nBundle\CacheWarmer\I18nWarmer
        arguments:
            - "@victoire_core.annotation_reader"
            - "%application_locales%"
        tags:
            - { name: kernel.cache_warmer, priority: 1}

    victoire_i18n.i18n.cache_driver:
        class: Victoire\Bundle\I18nBundle\CacheWarmer\I18nCacheDriver
        arguments:
            - "@annotation_reader"
            - "%kernel.cache_dir%"

    victoire_i18n.translator:
        class: Victoire\Bundle\I18nBundle\Translation\Translator
        arguments: ["@service_container", "@translator.selector",{}, {cache_dir:"%kernel.cache_dir%/translations%", debug: "%kernel.debug%"}]
    
    victoire_i18n.locale_listener:
        class: Victoire\Bundle\I18nBundle\Listener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }


    victoire_i18n.template_menu.contextual:
        class: Victoire\Bundle\I18nBundle\Listener\I18nTemplateMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.template_menu.contextual, method: addContextual }
