services:

    victoire_i18n.locale_resolver:
        class: Victoire\Bundle\I18nBundle\Resolver\LocaleResolver
        arguments: ['%locale_pattern%', '%locale_pattern_table%', '%locale%']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    victoire_i18n.menu_listener:
        class: Victoire\Bundle\I18nBundle\Listener\I18nMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.page_menu.contextual, method: addContextual, priority: 100 }

    victoire_i18n.url.resolver:
        class: Victoire\Bundle\I18nBundle\Resolver\UrlResolver
        arguments: ["@victoire_page.page_helper", "@doctrine.orm.entity_manager"]

    victoire_i18n.cache_warmer.i18n_warmer:
        class: Victoire\Bundle\I18nBundle\CacheWarmer\I18nWarmer
        arguments:
            - "@victoire_core.annotation_reader"
            - "%application_locales%"
        tags:
            - { name: kernel.cache_warmer, priority: 1}

    victoire_i18n.i18n.cache_driver:
        class: Victoire\Bundle\I18nBundle\CacheWarmer\I18nCacheDriver
        arguments:
            - "@annotation_reader"
            - "%kernel.cache_dir%"

    victoire_i18n.i18n.subscriber:
        class: Victoire\Bundle\I18nBundle\EventSubscriber\I18nSubscriber
        calls:
            - [ setAnnotationReader, ["@victoire_i18n.annotation_reader"] ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

      victoire_i18n.annotation_reader:
        class: Victoire\Bundle\I18nBundle\Annotations\Reader\AnnotationReader
        arguments:
            - "@annotation_reader"
            - "%kernel.root_dir%"
        calls:
            - [ setCache, ["@victoire_core.apc.cache"] ]
