services:
    victoire_business_entity_template.helper.business_entity_template_helper:
        class: Victoire\Bundle\BusinessEntityTemplateBundle\Helper\BusinessEntityTemplateHelper
        arguments: 
            - "@doctrine.orm.entity_manager"