services:
    victoire_business_entity_template.business_entity_template.form.type:
        class: Victoire\Bundle\BusinessEntityTemplateBundle\Form\BusinessEntityTemplateType
        arguments:
            - "%victoire_core.layouts%"
        tags:
            - { name: form.type, alias: victoire_business_entity_template_type }

    victoire_business_entity_template.business_entity_template_menu_listener:
        class: Victoire\Bundle\BusinessEntityTemplateBundle\Listener\BusinessEntityTemplateMenuListener
        arguments:
            - "@victoire_core.admin_menu_builder"
        tags:
            - { name: kernel.event_listener, event: victoire_core.build_menu, method: addGlobal, priority: 50 }

    victoire_core.businessEntityTemplate_menu.contextual:
        class: Victoire\Bundle\BusinessEntityTemplateBundle\Listener\BusinessEntityTemplateMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.businessEntityTemplate_menu.contextual, method: addContextual }

    victoire_business_entity_template.business_entity_template_helper:
        class: Victoire\Bundle\BusinessEntityTemplateBundle\Helper\BusinessEntityTemplateHelper
        arguments:
            - "@victoire_query.query_helper"
            - "@victoire_core.helper.business_entity_helper"
            - "@victoire_business_entity.converter.parameter_converter"

