services:
    victoire_business_entity_template.helper.business_entity_template_helper:
        class: Victoire\Bundle\BusinessEntityTemplateBundle\Helper\BusinessEntityTemplateHelper
        arguments: 
            - "@doctrine.orm.entity_manager"
            
    victoire_business_entity_template.business_entity_template.form.type:
        class: Victoire\Bundle\BusinessEntityTemplateBundle\Form\BusinessEntityTemplateType
        arguments: 
            - "%victoire_core.layouts%"
        tags:
            - { name: form.type, alias: victoire_business_entity_template_type }
            
    victoire_business_entity_template.business_entity_template_menu_listener:
        class: Victoire\Bundle\BusinessEntityTemplateBundle\Listener\BusinessEntityTemplateMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]