parameters:
    victoire_business_page.BusinessTemplate_chain.class: Victoire\Bundle\BusinessEntityPageBundle\Chain\BusinessTemplateChain
    victoire_business_page.BusinessTemplate_chain.BusinessTemplate.class: Victoire\Bundle\BusinessEntityPageBundle\Entity\BusinessTemplate

services:
    victoire_business_page.business_template.form.type:
        class: Victoire\Bundle\BusinessEntityPageBundle\Form\BusinessTemplateType
        arguments:
            - "%victoire_i18n.available_locales%"
            - "@request_stack"
        tags:
            - { name: form.type, alias: victoire_business_template_type }

    victoire_business_page.business_page.form.type:
        class: Victoire\Bundle\BusinessEntityPageBundle\Form\BusinessPageType
        arguments:
            - "%victoire_i18n.available_locales%"
            - "@request_stack"
        tags:
            - { name: form.type, alias: victoire_business_page_type }


    victoire_business_page.business_page_helper:
        class: Victoire\Bundle\BusinessEntityPageBundle\Helper\BusinessPageHelper
        arguments:
            - "@victoire_query.query_helper"
            - "@victoire_core.view_cache_helper"
            - "@victoire_core.helper.business_entity_helper"
            - "@victoire_business_entity.converter.parameter_converter"
            - "@doctrine.orm.entity_manager"

    victoire_business_page.BusinessTemplate_chain:
        class: "%victoire_business_page.BusinessTemplate_chain.class%"

    victoire_business_page.BusinessTemplate_chain.BusinessTemplate:
        class: "%victoire_business_page.BusinessTemplate_chain.BusinessTemplate.class%"
        tags:
            -  { name: victoire_core.bussinessEntityPagePattern, alias: default }

    ####################################################################################################################
    # Menu
    ####################################################################################################################
    victoire_business_page.business_template_menu_listener:
        class: Victoire\Bundle\BusinessEntityPageBundle\Listener\BusinessPageMenuListener
        arguments:
            - "@victoire_core.admin_menu_builder"
        tags:
            - { name: kernel.event_listener, event: victoire_core.build_menu, method: addGlobal, priority: 50 }

    victoire_core.business_template_menu.contextual:
        class: Victoire\Bundle\BusinessEntityPageBundle\Listener\BusinessPageMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.business_template_menu.contextual, method: addContextual }
