services:
    victoire_widget.widget_map_builder:
        class: Victoire\Bundle\PageBundle\WidgetMap\WidgetMapBuilder
        arguments: [@doctrine.orm.entity_manager]

    victoire_widget.widget_content_resolver:
        class: Victoire\Bundle\WidgetBundle\Resolver\WidgetContentResolver
        arguments:
            - @victoire_widget.widget_content_resolver_chain

    victoire_widget.base_widget_content_resolver:
        class: Victoire\Bundle\WidgetBundle\Resolver\BaseWidgetContentResolver
        calls:
            - [setQueryHelper, ["@victoire_query.query_helper"]]

    victoire_widget.widget_helper:
        class: Victoire\Bundle\WidgetBundle\Helper\WidgetHelper
        arguments: [@service_container]

    victoire_widget.widget_form_builder:
        class: Victoire\Bundle\WidgetBundle\Builder\WidgetFormBuilder
        arguments: [@service_container]

    victoire_widget.widget_renderer:
        class: Victoire\Bundle\WidgetBundle\Renderer\WidgetRenderer
        arguments: [@service_container]

    victoire_widget.widget_manager:
        class: Victoire\Bundle\WidgetBundle\Model\WidgetManager
        arguments:
            - @victoire_widget.widget_helper
            - @victoire_widget.widget_form_builder
            - @victoire_widget.widget_content_resolver
            - @victoire_widget.widget_renderer
            - @doctrine.orm.entity_manager
            - @victoire_form.error_helper
            - @request
            - @victoire_widget_map.manager
            - @victoire_widget_map.helper
            - @victoire_widget_map.builder
            - @victoire_core.annotation_reader
            - @victoire_core.template_mapper
            - @victoire_page.page_helper
            - %victoire_core.slots%
            - @service_container
        scope: request

    widget_manager:
        alias: victoire_widget.widget_manager

    victoire_widget.widget_content_resolver_chain:
        class: Victoire\Bundle\WidgetBundle\Resolver\Chain\WidgetContentResolverChain
        arguments:
            - @victoire_widget.widget_helper
    victoire_widget.twig.link_extension:
        class: Victoire\Bundle\WidgetBundle\Twig\LinkExtension
        arguments:
            - @router
            - @request_stack
            - %victoire_seo.analytics%
        tags:
            - { name: twig.extension }
