services:
    victoire_criteria.chain.criteria_chain:
        class: Victoire\Bundle\CriteriaBundle\Chain\CriteriaChain


    victoire_criteria.criteria.base_criteria:
        class: Victoire\Bundle\CriteriaBundle\Criteria\BaseCriteria
        tags:
            - { name: victoire_criteria, alias: default }

    victoire_criteria.criteria.request_criteria:
        class: Victoire\Bundle\CriteriaBundle\Criteria\RequestCriteria
        arguments: [ @request_stack ]
        tags:
            - { name: victoire_criteria, alias: locale }
            - { name: victoire_criteria, alias: scheme }
