
VictoireCoreBundle:
    resource: "@VictoireCoreBundle/Controller/"
    type:     annotation
    prefix:   /


victoire_core_page_show:
    path:      /{url}
    defaults:  { _controller: VictoirePageBundle:Page:show }
    requirements:
        url:  ^.*$
