parameters:
    router.options.generator_base_class: Victoire\Bundle\CoreBundle\Route\UrlGenerator

services:

#  ==================  Widgets ================== #
    victoire_core.entity_proxy.fields_builder:
        class: Victoire\Bundle\CoreBundle\Form\Builder\EntityProxyFieldsBuilder
        arguments:
            - @victoire_core.annotation_reader
            - @translator

#  ==================  MENU ================== #
    victoire_core.admin_menu_builder:
        class: Victoire\Bundle\CoreBundle\Menu\MenuBuilder
        arguments: [ '@knp_menu.factory', '@security.context' ]

    victoire_core.admin_menu:
        class: Knp\Menu\MenuItem
        factory_service: victoire_core.admin_menu_builder
        factory_method: getMenu
        scope: request
        tags:
            - { name: knp_menu.menu, alias: admin_menu }

    victoire_core.admin_menu.navbar_top:
        class: Knp\Menu\MenuItem
        factory_service: victoire_core.admin_menu_builder
        factory_method: getTopNavbar
        scope: request
        tags:
            - { name: knp_menu.menu, alias: topnavbar }

    victoire_core.admin_menu.navbar_left:
        class: Knp\Menu\MenuItem
        factory_service: victoire_core.admin_menu_builder
        factory_method: getLeftNavbar
        scope: request
        tags:
            - { name: knp_menu.menu, alias: leftnavbar }

    victoire_core.menu_dispatcher:
        class: Victoire\Bundle\CoreBundle\Listener\MenuDispatcher
        arguments:
            - "@event_dispatcher"
            - "@security.context"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    victoire_core.backend_menu_listener:
        class: Victoire\Bundle\CoreBundle\Listener\BackendMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.backend_menu.global, method: addGlobal, priority: 100 }

    victoire_core.listener.controller_listener:
        class: Victoire\Bundle\CoreBundle\Listener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: preExecuteAutorun }

#  ==================  Template ================== #
    victoire_core.template_mapper:
        class: Victoire\Bundle\CoreBundle\Template\TemplateMapper
        arguments: ["@service_container"]

    victoire_templating:
        alias: victoire_core.template_mapper

#  ==================  Twig ================== #
    victoire_core.twig.cms_extension:
        class: Victoire\Bundle\CoreBundle\Twig\Extension\CmsExtension
        arguments:
            - "@Victoire_widget.widget_renderer"
            - "@victoire_templating"
            - "@security.context"
            - "@doctrine.orm.entity_manager"
            - "@victoire_core.widget_exception_handler"
            - "@victoire_core.current_view"
            - "@victoire_core.view_cache_helper"
            - "@twig"
        tags:
            - { name: twig.extension }

    victoire_core.twig.globals_extension:
        class: Victoire\Bundle\CoreBundle\Twig\Extension\GlobalsExtension
        arguments:
            - "@victoire_templating"
            - "@session"
        tags:
            - { name: twig.extension }

#  ==================  Cache ================== #

    victoire_core.apc.cache:
        class: Victoire\Bundle\CoreBundle\Cache\ApcCache
        arguments:
            - "%doctrine.orm.cache.apc.class%"
            - "%kernel.debug%"
            - "@file_locator"

    victoire_core.view_cache_helper:
        class: Victoire\Bundle\CoreBundle\Helper\ViewCacheHelper
        arguments:
            - "%kernel.cache_dir%"
            - "@request_stack"
        calls:
            - [ setContainer, ["@service_container"] ]


    victoire_core.view_cache_listener:
        class: Victoire\Bundle\CoreBundle\Listener\ViewCacheListener
        arguments:
            - "@victoire_core.view_helper"
            - "@victoire_core.view_cache_helper"
            - "%kernel.debug%"
            - "%victoire_core.watch_view_cache%"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

#  ==================  Annotations ================== #

    victoire_core.annotation_reader:
        class: Victoire\Bundle\CoreBundle\Annotations\Reader\AnnotationReader
        arguments:
            - "@annotation_reader"
            - "@victoire_widget.widget_helper"
            - "%kernel.root_dir%"
            - "%victoire_core.widgets%"
        calls:
            - [ setCache, ["@victoire_core.apc.cache"] ]

#  ==================  Subscribers ================== #

    victoire_core.widget_discriminator_map.subscriber:
        class: Victoire\Bundle\CoreBundle\EventSubscriber\WidgetDiscriminatorMapSubscriber
        calls:
            - [ setWidgets, ["%victoire_core.widgets%"] ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    victoire_core.entity_proxy.subscriber:
        class: Victoire\Bundle\CoreBundle\EventSubscriber\EntityProxySubscriber
        calls:
            - [ setAnnotationReader, ["@victoire_core.annotation_reader"] ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }


#  ==================  Cache =================== #

    victoire_core.cache_warmer.entity_proxy_warmer:
        class: Victoire\Bundle\CoreBundle\CacheWarmer\EntityProxyWarmer
        arguments:
            - "@victoire_core.annotation_reader"
            - "@file_locator"
        tags:
            - { name: kernel.cache_warmer, priority: 1}

    victoire_core.cache_warmer.view_warmer:
        class: Victoire\Bundle\CoreBundle\CacheWarmer\ViewCacheWarmer
        arguments:
            - @victoire_core.view_helper
            - @victoire_core.view_cache_helper
        tags:
        - { name: kernel.event_listener, event: kernel.request, method: warmUp }

    victoire_core.entity_proxy.cache_driver:
        class: Victoire\Bundle\CoreBundle\CacheWarmer\EntityProxyCacheDriver
        arguments:
            - "@annotation_reader"
            - "%kernel.cache_dir%"

    victoire_core.helper.business_entity_helper:
        class: Victoire\Bundle\BusinessEntityBundle\Helper\BusinessEntityHelper
        arguments:
            - "@victoire_core.annotation_reader"
            - "@doctrine.orm.entity_manager"

#  ==================  Error handler =================== #

    victoire_core.widget_exception_handler:
        class: Victoire\Bundle\CoreBundle\Handler\WidgetExceptionHandler
        arguments:
            - "@security.context"
            - "@twig"
            - "%kernel.debug%"
            - "@victoire_templating"

#  ==================  View ================== #


    victoire_core.view_helper:
        class: Victoire\Bundle\CoreBundle\Helper\ViewHelper
        arguments:
            - "@victoire_business_entity.converter.parameter_converter"
            - "@victoire_core.helper.business_entity_helper"
            - "@victoire_business_entity_page.business_entity_page_helper"
            - "@doctrine.orm.entity_manager"
            - "@victoire_core.view_cache_helper"

    victoire_core.current_view:
        class: Victoire\Bundle\CoreBundle\Helper\CurrentViewHelper


    twig.extension.routing:
        class: 'Victoire\Bundle\CoreBundle\Twig\Extension\RoutingExtention'
        public: false
        arguments:
            - '@victoire_page.page_helper'
            - '@router'

    victoire_core.routing_loader:
        class: Victoire\Bundle\CoreBundle\Route\RouteLoader
        arguments:
            - '%victoire_core.widgets%'
        tags:
            - { name: routing.loader }
