parameters:
    router.options.generator_base_class: Victoire\Bundle\CoreBundle\Route\UrlGenerator

services:
    # av_assetic_injector.collector_engine.require_victoire:
    #     class: "Victoire\Bundle\CoreBundle\AssetsCollector\RequireVictoire"
    #     arguments: [@service_container]

    # assetic_injector.require_victoire:
    #     alias: av_assetic_injector.collector_engine.require_victoire

#  ==================  Widgets ================== #
    victoire_core.twig.widget_manager:
        class: Victoire\Bundle\CoreBundle\Widget\Managers\WidgetManager
        arguments: 
            - "@service_container"
            - "@page.widgetMap.builder"
            - "@av.form_error_service"

    widget_manager:
        alias: victoire_core.twig.widget_manager

    widget.subscriber:
        class: Victoire\Bundle\CoreBundle\EventSubscriber\WidgetSubscriber
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_subscriber }

    victoire_core.entity_proxy.fields_builder:
        class: Victoire\Bundle\CoreBundle\Form\Builder\EntityProxyFieldsBuilder
        arguments: ["@victoire_core.annotation_reader"]
    victoire_core.widget_helper:
        class: Victoire\Bundle\CoreBundle\Helper\WidgetHelper
        arguments:
            - "@doctrine.orm.entity_manager"
#  ==================  MENU ================== #

    victoire_core.admin_menu_builder:
        class: Victoire\Bundle\CoreBundle\Menu\MenuBuilder
        arguments: [ '@knp_menu.factory', '@security.context' ]

    victoire_core.admin_menu:
        class: Knp\Menu\MenuItem
        factory_service: victoire_core.admin_menu_builder
        factory_method: getMenu
        scope: request
        tags:
            - { name: knp_menu.menu, alias: admin_menu }

    victoire_core.admin_menu.navbar_top:
        class: Knp\Menu\MenuItem
        factory_service: victoire_core.admin_menu_builder
        factory_method: getTopNavbar
        scope: request
        tags:
            - { name: knp_menu.menu, alias: topnavbar }

    victoire_core.admin_menu.navbar_left:
        class: Knp\Menu\MenuItem
        factory_service: victoire_core.admin_menu_builder
        factory_method: getLeftNavbar
        scope: request
        tags:
            - { name: knp_menu.menu, alias: leftnavbar }

    victoire_core.menu_listener:
        class: Victoire\Bundle\CoreBundle\Listener\MenuListener
        arguments:
            - "@event_dispatcher"
            - "@victoire_core.page_menu_listener"
            - "@victoire_core.template_menu_listener"
            - "@victoire_core.sitemap_menu_listener"
            - "@victoire_business_entity_template.business_entity_template_menu_listener"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    victoire_core.sitemap_menu_listener:
        class: Victoire\Bundle\CoreBundle\Listener\SiteMapMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]

#  ==================  Template ================== #
    victoire_core.template_mapper:
        class: Victoire\Bundle\CoreBundle\Template\TemplateMapper
        arguments: ["@service_container"]

    victoire_templating:
        alias: victoire_core.template_mapper

#  ==================  Twig ================== #
    victoire_core.twig.cms_extension:
        class: Victoire\Bundle\CoreBundle\Twig\Extension\CmsExtension
        arguments: 
            - "@widget_manager"
            - "@victoire_templating"
            - "@security.context" 
            - "@victoire_core.widget_helper"
            - "@page.widgetMap.builder"
        tags:
            - { name: twig.extension }
    victoire_core.twig.globals_extension:
        class: Victoire\Bundle\CoreBundle\Twig\Extension\GlobalsExtension
        arguments: 
            - "@victoire_templating"
            - "@session"
        tags:
            - { name: twig.extension }

#  ==================  Cache ================== #

    victoire_core.apc.cache:
        class: Victoire\Bundle\CoreBundle\Cache\ApcCache
        arguments: 
            - "%doctrine.orm.cache.apc.class%"
            - "%kernel.debug%"

#  ==================  Routing ================== #

    victoire_core.routing.loader.cache:
        class: Victoire\Bundle\CoreBundle\Route\CacheRouteLoader
        arguments: 
            - "@victoire_core.cache.route_registerer"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: routing.loader }

    victoire_core.cache.route_registerer:
        class: Victoire\Bundle\CoreBundle\Route\CacheRouteRegisterer
        arguments: 
            - "@victoire_core.apc.cache"
#  ==================  Annotations ================== #

    victoire_core.annotation_reader:
        class: Victoire\Bundle\CoreBundle\Annotations\Reader\AnnotationReader
        arguments: 
            - "@annotation_reader"
            - "%kernel.root_dir%" 
            - "%victoire_core.widgets%"
        calls:
            - [ setCache, ["@victoire_core.apc.cache"] ]


#  ==================  Theme ================== #

    victoire_core.theme_chain:
        class: Victoire\Bundle\CoreBundle\Theme\ThemeChain
        arguments:
            - "%victoire_core.widgets%"

#  ==================  Subscribers ================== #

    victoire_core.widget_discriminator_map.subscriber:
        class: Victoire\Bundle\CoreBundle\EventSubscriber\WidgetDiscriminatorMapSubscriber
        calls:
            - [ setWidgets, ["%victoire_core.widgets%"] ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    victoire_core.entity_proxy.subscriber:
        class: Victoire\Bundle\CoreBundle\EventSubscriber\EntityProxySubscriber
        calls:
            - [ setAnnotationReader, ["@victoire_core.annotation_reader"] ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }


#  ==================  Cache =================== #

    victoire_core.cache_warmer.entity_proxy_warmer:
        class: Victoire\Bundle\CoreBundle\CacheWarmer\EntityProxyWarmer
        arguments:
            - "@victoire_core.annotation_reader"
        tags:
            - { name: kernel.cache_warmer}

    victoire_core.entity_proxy.cache_driver:
        class: Victoire\Bundle\CoreBundle\CacheWarmer\EntityProxyCacheDriver
        arguments: 
            - "@annotation_reader"
            - "%kernel.root_dir%"
            - "%kernel.environment%"

    victoire_core.helper.business_entity_helper:
        class: Victoire\Bundle\CoreBundle\Helper\BusinessEntityHelper
        arguments: 
            - "@victoire_core.annotation_reader"
            - "@doctrine.orm.entity_manager"

    #  ==================  Error handler =================== #

    victoire_core.widget_exception_handler:
        class: Victoire\Bundle\CoreBundle\Handler\WidgetExceptionHandler
        arguments: 
            - "@security.context"
            - "@templating"
            - "%kernel.debug%"
            
